### ISSUE TITLE
Redux Testing

### ISSUE THREAD

**Issue by hfaerber** [peeratmac/rancid-tomatillos#29]
Redux Testing

**Comment by Dunn-Austen** [comment]
##Redux Testing
**Action Creator Tests:**
- [ ] ADD_MOVIES 
- [ ] UPDATE_USER (will need additional tests for the eventual case we're introducing for updating ratings)
- [ ] HANDLE_ERROR
- [ ] IS_LOADING
- [ ] ... Tests for Action creators-to-be-added

**Reducer Tests:**
- [ ] ADD_MOVIES 
- [ ] UPDATE_USER (will need additional tests for the eventual case we're introducing for updating ratings)
- [ ] HANDLE_ERROR
- [ ] IS_LOADING
- [ ] ... Tests for Reducers-to-be-added

**map...ToProps tests for Container components:**
- [ ] LoginForm
- [ ] MovieContainer
- [ ] NavigationBar
- [ ]
-
