### ISSUE TITLE
Iteration 2 - User Login

### ISSUE THREAD

**Issue by peeratmac** [peeratmac/rancid-tomatillos#3]
~- /login page where user can login~
~- use POST for unique user ID *< Mostly done. Built in the apiCalls.js file - just needs combined with the form. HF*~
~- user should know they are loggedIn~
~- user does get taken back to / main route homepage where all the movies displayed~
@hfaerber

**Comment by peeratmac** [comment]
- **User assigned -- our PM has assigned us a user to use throughout the development phase:**  `{name: 'Marge', email: 'marge@turing.io', password: 'password123'}`

**Comment by hfaerber** [comment]
- POST Body will need to be `{"email":"marge@turing.io","password":"password123"}`
- POST response object will be `{
    "user": {
        "id": 9,
        "name": "Marge",
        "email": "marge@turing.io"
    }
}`

**Comment by Dunn-Austen** [comment]
The first bullet point of this issue has been completed (rough drafts of the Login Form and page are established)

**Comment by Dunn-Austen** [comment]
Closing this one out. All action items have been addressed
