### ISSUE TITLE
Let's create directories within components and containers

### ISSUE THREAD

**Issue by peeratmac** [peeratmac/rancid-tomatillos#32]
I think they are starting to get a little messy with the main JS file, CSS, and test files.

**This should get done later after we do iteration 4 and 5**  Feel free to comment here if you think otherwise.  @hfaerber @Dunn-Austen 

![image](https://user-images.githubusercontent.com/47256534/71211470-6f756b80-226c-11ea-8539-806b5ba41e72.png)

**Comment by Dunn-Austen** [comment]
As a note of clarity in this eventual process, all store-connected components should be migrated into the Containers folder.

**Comment by hfaerber** [comment]
@Dunn-Austen Thats a really good question.  I'm not sure of the answer.  @peeratmac Do you know?

**Comment by peeratmac** [comment]
@hfaerber Yes, that is correct.  We are going to move all that into the containers directory.

**Comment by Dunn-Austen** [comment]
Our files & directories have been reorganized. Closing this issue
