### ISSUE TITLE
Need to prevent user that isn't loggedIn from rating movies

### ISSUE THREAD

**Issue by peeratmac** [peeratmac/rancid-tomatillos#43]
@hfaerber @Dunn-Austen with my next PR, this is going to be a known issue for user that isn't loggedIn.  It will work fine for user who is loggedIn to update ratings in the redux store accordingly.

**Comment by peeratmac** [comment]
**The question is** whether we want to not show the ratings scale to rate altogether or do we want the scale to take to user to `/login`

**Comment by Dunn-Austen** [comment]
I'm leaning towards conditionally rendering the ratings scale so that it only appears post-login. I'll incorporate this approach into my work for the delete functionality. 

-AD

**Comment by Dunn-Austen** [comment]
Marking this closed. Resolved with conditional rendering.
