### ISSUE TITLE
Conditional error message display (2nd) in LoginForm needs updated or removed

### ISSUE THREAD

**Issue by hfaerber** [peeratmac/rancid-tomatillos#51]
@Dunn-Austen @peeratmac   No rush on this - just making a note so I don't forget when we get back to it this weekend.  I'm adding a snapshot for the conditional rendering for the LoginForm and realized that I don't know what line 61 should be doing?   

Based on how its written now it says `if there is NOT an error, display the errorMessage as an h1`  but if there is not an error, that will just be an empty string.  

Something to revisit when we're back at it.  Opening an issue so its on our PM board.

_Originally posted by @hfaerber in https://github.com/peeratmac/rancid-tomatillos/pull/46/review_comment/create_

**Comment by hfaerber** [comment]
As I work through unit testing I see that this error displays if the user clicks submit without completing the input fields.

**Comment by Dunn-Austen** [comment]
Please see PR comments for clarification. If there's no additional concern, please close the issue.

**Comment by hfaerber** [comment]
Thanks again Austen - closing now.
