### ISSUE TITLE
`Ratings` word disappears on edge case navigation

### ISSUE THREAD

**Issue by hfaerber** [peeratmac/rancid-tomatillos#63]
Found strange edge-case bug where `Ratings` does not display to the right of the tomato for the `Average Ratings` display on the homepage when user navigates to an invalid page then back to home.

**Comment by Dunn-Austen** [comment]
The glitch appears with irregular consistency. I've tried expanding the size of the containing element without luck. Some initial web research suggests that the relative positioning might be the culprit. I'll keep playing around with the issue, but haven't resolved it yet.

**Comment by Dunn-Austen** [comment]
I replaced the relative positioning rules with analogous code and the disappearing text problem has been solved. Closing this out
